config setup
   charondebug="ike 1, knl 1"

conn hsms-transport
    type=transport
    keyexchange=ikev2
    authby=secret
    
    left=10.99.0.1
    right=10.99.0.2

    ike=aes256-sha256-modp2048
    esp=aes256-sha256-modp2048

    auto=start
